Week 8/Day 5/Rental project/bike_scooter_rental/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('rent.urls'))
]

Week 8/Day 5/Rental project/rent/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('customer/', views.customer, name='customer'),

    path('add_customer/', views.add_customer, name='add_customer'),

    path('vehicle/', views.vehicle, name='vehicle'),

    path('add_vehicle/', views.add_vehicle, name='vehicle_add'),

  path('add_rental/', views.add_rental, name='add_rental'),

    ]

Week 8/Day 5/Rental project/rent/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django_group_by import GroupByMixin

class Customer(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    email=models.EmailField(max_length=100)
    phone_number=models.CharField(max_length=100)
    address=models.CharField(max_length=100)
    city=models.CharField(max_length=100)
    country=models.CharField(max_length=100)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'
# *________________________________________________________

class Vehicle(models.Model):
    vehicle_type=models.ForeignKey('VehicleType',on_delete=models.SET_NULL,null=True,related_name='type')
    date_creaeted=models.DateTimeField(auto_now_add=True)
    real_cost=models.FloatField()
    size=models.ForeignKey('VehicleSize',on_delete=models.SET_NULL,null=True,related_name='size')

    def __str__(self):
        return f'{str(self.vehicle_type)} Cost: {self.real_cost} $'
# *________________________________________________________

class VehicleType(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name
# *_________________________________________________________

class VehicleSize(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name
# *_________________________________________________________

class Rental(models.Model):
    rental_date=models.DateTimeField(auto_now_add=True)
    return_date=models.DateTimeField(null=False)
    customer=models.ForeignKey('Customer',on_delete=models.SET_NULL,null=True)
    vehicle=models.ForeignKey('Vehicle',on_delete=models.SET_NULL,null=True)

# *_________________________________________________________

class RentalRate(models.Model):
    daily_rate=models.FloatField(default=100)
    vehicle_type=models.ForeignKey('VehicleType',on_delete=models.SET_NULL,null=True)
    vehicle_size=models.ForeignKey('VehicleSize',on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return f'{self.vehicle_type} {self.daily_rate}'

# *_________________________________________________________

Week 8/Day 5/Rental project/rent/forms.py
from django import forms
from .models import *

class AddVehicleForm(forms.Form):
    vehicle_type=forms.CharField(max_length=20)
    vehicle_size=forms.CharField(max_length=20)
    vehicle_cost=forms.FloatField()
# *________________________________________________

def vehicle_type():
    vehicle_type=VehicleType.objects.all()
    vehicle_type = [(vehicle.name ,vehicle.name.upper) for vehicle in vehicle_type]
    return vehicle_type

def customer():
    all_customers=Customer.objects.all()  
    names=[(f'{customer.first_name} {customer.last_name}',f'{customer.first_name} {customer.last_name}') for customer in all_customers]
    return names

def vehicle_size():
    vehicle_size=VehicleSize.objects.all()
    vehicle_size=[(vehicle.name,vehicle.name.upper) for vehicle in vehicle_size]
    return vehicle_size    

class AddRentalForm(forms.Form):
    vehicle_type=forms.ChoiceField(choices=vehicle_type())
    vehicle_size=forms.ChoiceField(choices=vehicle_size())
    customer=forms.ChoiceField(choices=customer())

# *________________________________________________
class AddCustomerForm(forms.Form):
    first_name=forms.CharField(max_length=30)
    last_name=forms.CharField(max_length=30)
    email=forms.EmailField(max_length=100)
    phone_number=forms.CharField(max_length=100)
    address=forms.CharField(max_length=100)
    city=forms.CharField(max_length=100)
    country=forms.CharField(max_length=100)


    

Week 8/Day 5/Rental project/rent/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *


def customer(request):
    customers=Customer.objects.all().order_by('last_name')
    return render(request,'customer.html',{'customers':customers})
# *_________________________________________________________

def vehicle(request):
    vehicles=VehicleType.objects.all()
    context={
        'vehicles':vehicles,  
    }
    return render (request,'vehicle.html',context)
# *_________________________________________________________
def check_vehicle(vehicle_type):
    all_vehicles=VehicleType.objects.all()
    for vehicle in all_vehicles:
        if vehicle.name == vehicle_type:
            return vehicle
    
def check_vehicle_size(vehicle_size):
    vehicle_sizes=VehicleSize.objects.all()
    for vehicle in vehicle_sizes:
        if vehicle.name == vehicle_size:
            return vehicle
    
def add_vehicle(request):
    my_form=AddVehicleForm()

    if request.method =='GET':
        return render(request,'add_vehicle.html',{'add_vehicle':my_form})

    if request.method=='POST':
        myform=AddVehicleForm(request.POST)

        if myform.is_valid():
            vehicle_type=myform.cleaned_data['vehicle_type']
            vehicle_size=myform.cleaned_data['vehicle_size']
            vehicle_cost=myform.cleaned_data['vehicle_cost']

      
            cost=Vehicle(real_cost=vehicle_cost,vehicle_type=check_vehicle(vehicle_type),size=check_vehicle_size(vehicle_size))
            cost.save()
       

            return redirect('vehicle')    
# *_________________________________________________________

def add_rental(request):
    my_form=AddRentalForm()
    if request.method=='GET':
        return render(request,'new_rental.html',{'add_rental':my_form})

#     if request.method=='POST'
#         my_form=AddRentalForm(request.POST)
#         all_customers[customer.id for customer in] 

#             if my_form is_valid():


def add_customer(request):
    my_form=AddCustomerForm()

    if request.method=='GET':
        return render(request,'add_customer.html',{'add_customer':my_form})

    if request.method=='POST':
        my_form=AddCustomerForm(request.POST)
        if my_form.is_valid():
            first_name=my_form.cleaned_data['first_name']
            last_name=my_form.cleaned_data['last_name']
            email=my_form.cleaned_data['email']
            phone_number=my_form.cleaned_data['phone_number']
            address=my_form.cleaned_data['address']
            city=my_form.cleaned_data['city']
            country=my_form.cleaned_data['country']

            new_customer=Customer(first_name=first_name,last_name=last_name,email=email,phone_number=phone_number,address=address,city=city,country=country)
            new_customer.save()

            return redirect('customer')

        else:
         return render(request,'add_customer.html',{'add_customer':my_form})        



        







        

Week 8/Day 5/Rental project/rent/templates/add_customer.html
{%extends 'base.html'%}
{%block content%}
<form method="POST" >
    {%csrf_token%}
    <div class="form-group">
        <table>
            {{add_customer.as_table}}
            <input type="submit">
        </table>     
    </div>
</form>
{%endblock%}

Week 8/Day 5/Rental project/rent/templates/add_vehicle.html
{%extends 'base.html'%}

{% block content %}
<form method="POST">
    {%csrf_token%}
    <table>
        {{add_vehicle.as_table}}
    </table>
    <input type="submit">
</form>


{% endblock %}

Week 8/Day 5/Rental project/rent/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Main</title>
</head>
<body>
    <h1>navbar</h1>
    <hr>
    {% block content %}
    {% endblock %}
    <hr>
    <h2>Footer</h2>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>
</html>

Week 8/Day 5/Rental project/rent/templates/customer.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Customers{% endblock %}
{% block content %}
<table class="table table-hover">
    <tr>
        <th>Lastname</th>
        <th>Firstname</th>
        <th>Email</th>
        <th>City</th>
        <th>Phone</th>
    </tr>
    {% for customer in customers %}
    <tr>
        <td>{{customer.last_name}}</td>
        <td>{{customer.first_name}}</td>
        <td>{{customer.email}}</td>
        <td>{{customer.city}}</td>
        <td>{{customer.phone_number}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

Week 8/Day 5/Rental project/rent/templates/new_rental.html
{%extends 'base.html'%}

{% block content %}
<table>
    <form method="POST">
        {{add_rental.as_table}}
        <input type="submit">
    </form>
</table>

{% endblock %}

Week 8/Day 5/Rental project/rent/templates/vehicle.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Vehicles{% endblock %}
{% block content %}
<h1>All vehicles</h1>
{% for vehicle in vehicles %}
<div style="display: inline-flex;">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>{{vehicle.name}}</th>
            </tr>
        </thead>
        <tbody>
            {% for v in vehicle.vehicle_set.all %}
            <tr>
                <td>
                    {{v.size}}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endfor %}
{% endblock %}